apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.2.4
          ports:
            - containerPort: 8080

