apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: public.ecr.aws/aws-containers/retail-store-sample-orders:1.2.4
          ports:
            - containerPort: 8080

