apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: retail
  name: developer-readonly
rules:
- apiGroups: ["", "apps", "extensions", "batch"]
  resources: ["pods", "services", "deployments", "replicasets", "configmaps", "secrets", "jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-readonly-binding
  namespace: retail
subjects:
- kind: User
  name: innovatemart-developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-readonly
  apiGroup: rbac.authorization.k8s.io
